# Site
name: "Stateless.my"
title: "Stateless.my"
description: "We believe that citizenship should not be exclusively proven via papers. Every Malaysians can be stateless, every stateless person can be Malaysian."
logo: 'assets/images/flag-2.png'
favicon: 'assets/images/flag-2.png'
baseurl: /
google_analytics: 'G-K2MT1WSBEY'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: yewlee456@gmail.com #not working formspree

# Authors
authors:
  wyl:
    name: Wong Yew Lee
    display_name: Wong Yew Lee
    avatar: 'assets/images/avatar-wyl.png'
    email: yewlee456@gmail.com
    web: http://cv.1906837.xyz/
    # twitter: https://twitter.com/wowthemesnet
    facebook: https://www.facebook.com/yewleew/
    instagram: https://instagram.com/wongyewlee/
    description: "Convenor of Stateless.my, stateless Malaysian. Stateless by paper, Malaysian by heart."

  nkj:
    name: Ng Khai Jie
    display_name: Ng Khai Jie
    avatar: 'assets/images/avatar-nkj.jpg'
    facebook: https://www.facebook.com/Jack.Ng.Khai.Jie
    description: "Born a stateless, Live a stateless, Die a Malaysian."

  mcra:
    name: Malaysian Citizenship Rights Alliance (MCRA)
    display_name: Malaysian Citizenship Rights Alliance (MCRA)
    # avatar: 'assets/images/avatar-nkj.jpg'
    # facebook: https://www.facebook.com/Jack.Ng.Khai.Jie
    # description: "Born a stateless, Live a stateless, Die a Malaysian."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
